# Auto-generated using compose2nix v0.3.2-pre.
{ config, pkgs, lib, ... }:

{
  age.secrets.paperless-env.file = ../../../../secrets/paperless-env.age;

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."paperless-broker" = {
    image = "docker.io/library/redis:8";
    volumes = [
      "paperless_redisdata:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=broker"
      "--network=paperless_default"
    ];
  };
  systemd.services."docker-paperless-broker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-paperless_default.service"
      "docker-volume-paperless_redisdata.service"
    ];
    requires = [
      "docker-network-paperless_default.service"
      "docker-volume-paperless_redisdata.service"
    ];
    partOf = [
      "docker-compose-paperless-root.target"
    ];
    wantedBy = [
      "docker-compose-paperless-root.target"
    ];
  };

  virtualisation.oci-containers.containers."paperless-webserver" = {
    image = "ghcr.io/paperless-ngx/paperless-ngx:latest";
    environment = {
      "PAPERLESS_REDIS" = "redis://broker:6379";
    };
    environmentFiles = [
        config.age.secrets.paperless-env.path
    ];
    volumes = [
      "paperless_data:/usr/src/paperless/data:rw"
      "paperless_media:/usr/src/paperless/media:rw"
    ];
    ports = [
      "10.0.0.5:8000:8000/tcp"
    ];
    dependsOn = [
      "paperless-broker"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=webserver"
      "--network=paperless_default"
    ];
  };
  systemd.services."docker-paperless-webserver" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-paperless_default.service"
      "docker-volume-paperless_data.service"
      "docker-volume-paperless_media.service"
    ];
    requires = [
      "docker-network-paperless_default.service"
      "docker-volume-paperless_data.service"
      "docker-volume-paperless_media.service"
    ];
    partOf = [
      "docker-compose-paperless-root.target"
    ];
    wantedBy = [
      "docker-compose-paperless-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-paperless_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f paperless_default";
    };
    script = ''
      docker network inspect paperless_default || docker network create paperless_default
    '';
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-paperless_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect paperless_data || docker volume create paperless_data
    '';
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };
  systemd.services."docker-volume-paperless_media" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect paperless_media || docker volume create paperless_media
    '';
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };
  systemd.services."docker-volume-paperless_redisdata" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect paperless_redisdata || docker volume create paperless_redisdata
    '';
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-paperless-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
