server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}

server {
    listen 80;
    server_name flatnotes.ad.dlandau.nl;

    location / {
        proxy_pass http://172.17.0.2:8080;
    }
}

server {
    listen 443 ssl;
    server_name             flatnotes.ad.dlandau.nl;
    ssl_certificate         /etc/certificates/flatnotes.ad.dlandau.nl/cert.pem;
    ssl_certificate_key     /etc/certificates/flatnotes.ad.dlandau.nl/key.pem;

    location / {
        proxy_pass http://172.17.0.2:8080;
    }
}
