server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}

server {
    listen 80;
    server_name flatnotes.ad.dlandau.nl;

    allow 10.0.0.0/24;
    deny all;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name             flatnotes.ad.dlandau.nl;
    ssl_certificate         /etc/certificates/flatnotes.ad.dlandau.nl/cert.pem;
    ssl_certificate_key     /etc/certificates/flatnotes.ad.dlandau.nl/key.pem;

    allow 10.0.0.0/24;
    deny all;

    location / {
        proxy_pass http://10.0.0.5:8080;
    }
}

server {
    listen 80;
    server_name paperless.ad.dlandau.nl;

    allow 10.0.0.0/24;
    deny all;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name             paperless.ad.dlandau.nl;
    ssl_certificate         /etc/certificates/paperless.ad.dlandau.nl/cert.pem;
    ssl_certificate_key     /etc/certificates/paperless.ad.dlandau.nl/key.pem;

    allow 10.0.0.0/24;
    deny all;

    location / {
        proxy_pass http://10.0.0.5:8000;
    }
}

server {
    listen 80;
    server_name timer.ad.dlandau.nl;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name             timer.ad.dlandau.nl;
    ssl_certificate         /etc/certificates/timer.ad.dlandau.nl/cert.pem;
    ssl_certificate_key     /etc/certificates/timer.ad.dlandau.nl/key.pem;

    root   /usr/share/time-logger;

    location / {
        index  index.html;
    }
}
